version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY}api
    build:
      context: .
      dockerfile: Api/Dockerfile
  web:
    image: ${DOCKER_REGISTRY}web
    build:
      context: .
      dockerfile: Web/Dockerfile





